name: Github actions QtCore

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    timeout-minutes: 360
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/moses-linux

    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v3
    -
      name: Moses Up
      run: |
        echo "${{ github.workspace }}" >> $GITHUB_PATH
        sudo apt-get update
        sudo apt-get install libexpat1
        sudo chmod +x moses
        sudo chmod +x tdskt
        sudo ./moses &
        sleep 15
    -
      name: EULA Accept
      run: |
        sudo ./tdskt platforms
        sudo ./tdskt eula nxp-la-opt-v5 setprop accepted true
        sudo ./tdskt platforms
    -
      name: Enable Emulation
      run: |
        ./tdskt -p enableemulation
    -
      name: Load Application
      run: |
        APPID=$(./tdskt load ../appconfig_0/)
        echo "APPID=$APPID" >> $GITHUB_ENV
    -
      name: Build SDK Container
      run: |
        ./tdskt -p application ${{ env.APPID }} runsdk release
    -
      name: Build Application
      run: |
        cd ..
        docker run --rm -t -v ${PWD}:/app --env-file \
        ./appconfig_0/containerEnv \
        qtcore_arm32v7-qt5-wayland-no-ssh_bullseye_release_${APPID}_sdk_image bash -c \
        "cd /app && arm-linux-gnueabihf-qmake CONFIG+=debug && make && make install"
    -
      name: Build Release Container
      run: |
        ./tdskt -p application ${{ env.APPID }} build release
